name: Sample Workflow

on:
  push:
    branches:
      - eks-cluster # Trigger this workflow on push to the main branch
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted # Use your self-hosted runner

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print Hello, World!
      run: echo "Hello, World!"
