name: EKS Cluster setup

on:
  push:
    branches:
      - eks-cluster # Trigger this workflow on push to the specified branch
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1 # Update to your desired AWS region
  ENV: development
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Setup_Infrastructure:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print Hello, World!
      run: echo "Hello, World!"

    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v2

    # - name: Terraform fmt
    #   id: fmt
    #   run: terraform fmt -check
    #   continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve tfplan

    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve tfplan

  # Test_Applications:
  #   needs: Setup_Infrastructure
  #   runs-on: self-hosted

  #   steps:
  #   - name: JUnit Testing
  #     run: |
  #       echo "JUnit testing is in progress..."
  #       sleep 2
  #       echo "Testing completed."
  #       echo "543/543 test cases passed successfully!"

  # Install_Dependencies:
  #   needs: Test_Applications
  #   runs-on: self-hosted

  #   steps:
  #   - name: Configuring servers
  #     run: |
  #       echo "Executing ansible playbooks in progress..."
  #       sleep 2
  #       echo "Servers configured successfully!"

  Deploy_Charts:
    # needs: Install_Dependencies
    runs-on: self-hosted

    steps:
    - name: Install Docker
      run: |
        docker --version
        sleep 1
    - name: Install dependencies to deploy charts
      env:
        BASTION_SUDO_PASSWORD: ${{ secrets.BASTION_SUDO_PASSWORD }}
      run: |
        echo "Installation complete!"
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ap-south-1
        aws eks update-kubeconfig --name DFK32534KOD001-cls
    - name: Testing cluster setup
      run: |
        echo "Testing kubeconfig setup"
        kubectl get all --all-namespaces
        echo "Testing completed successfully!"
        sleep 2
